services:
  ponger:
    image: end-to-end-testing:latest
    networks:
      test-network:
        ipv4_address: 172.20.0.10
    environment:
      - IOX2_LOG_LEVEL=Info
      - PINGER_ADDR=172.20.0.11:8080
    command: ["sh", "-c", "iox2-tunnel zenoh & sleep 1 && iceoryx2-tunnels-end-to-end-testing-ponger"]
    restart: "no"

  pinger:
    image: end-to-end-testing:latest
    networks:
      test-network:
        ipv4_address: 172.20.0.11
    environment:
      - IOX2_LOG_LEVEL=Info
      - PONGER_ADDR=172.20.0.10:8080
    command: ["sh", "-c", "iox2-tunnel zenoh & sleep 3 && iceoryx2-tunnels-end-to-end-testing-pinger"]
    restart: "no"

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
